-- MySQL Script generated by MySQL Workbench
-- Tue Feb 10 15:40:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema carcacas2_0
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carcacas2_0
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carcacas2_0` DEFAULT CHARACTER SET utf8mb4 ;
USE `carcacas2_0` ;

-- -----------------------------------------------------
-- Table `carcacas2_0`.`animal_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`animal_tipo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `animal` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`bezerro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`bezerro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(11) NOT NULL,
  `peso` DECIMAL(10,2) NOT NULL,
  `escala_lotes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `escala_lotes_id`),
  INDEX `fk_bezerro_escala_lotes1_idx` (`escala_lotes_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`causa_condenacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`causa_condenacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`escala_abate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`escala_abate` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data_abate` DATE NOT NULL,
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`escala_lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`escala_lotes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `lote` INT(11) NULL DEFAULT NULL,
  `escala_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `escala_id`),
  INDEX `escala_id` (`escala_id` ASC) VISIBLE,
  CONSTRAINT `escala_lotes_ibfk_1`
    FOREIGN KEY (`escala_id`)
    REFERENCES `carcacas2_0`.`escala_abate` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 151
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`condenacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`condenacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `peso` DOUBLE(10,2) NULL DEFAULT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `escala_lotes_id` INT(11) NOT NULL,
  `causa_condenacao_id` INT(11) NOT NULL,
  `gta` INT(11) NULL DEFAULT NULL,
  `animal_tipo` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `escala_lotes_id`, `causa_condenacao_id`),
  INDEX `fk_condenacao_escala_lotes1_idx` (`escala_lotes_id` ASC) VISIBLE,
  INDEX `fk_condenacao_causa_condenacao1_idx` (`causa_condenacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_condenacao_causa_condenacao1`
    FOREIGN KEY (`causa_condenacao_id`)
    REFERENCES `carcacas2_0`.`causa_condenacao` (`id`),
  CONSTRAINT `fk_condenacao_escala_lotes1`
    FOREIGN KEY (`escala_lotes_id`)
    REFERENCES `carcacas2_0`.`escala_lotes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`contusoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`contusoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sequencia` INT(11) NOT NULL,
  `data_registro` DATE NOT NULL,
  `lado` VARCHAR(20) NOT NULL,
  `intensidade` VARCHAR(20) NOT NULL,
  `regiao` VARCHAR(150) NOT NULL,
  `imagem` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8058
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`dif_limpeza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`dif_limpeza` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `escala_lote_id` INT(11) NOT NULL,
  `peso` DOUBLE(10,2) NOT NULL,
  `animal_tipo` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `escala_lote_id`),
  INDEX `escala_lote_id` (`escala_lote_id` ASC) VISIBLE,
  CONSTRAINT `dif_limpeza_ibfk_1`
    FOREIGN KEY (`escala_lote_id`)
    REFERENCES `carcacas2_0`.`escala_lotes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`foto_carcaca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`foto_carcaca` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sequencia` INT(11) NULL DEFAULT NULL,
  `imagem` MEDIUMTEXT NULL DEFAULT NULL,
  `classificacao` VARCHAR(45) NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_data` (`data` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 33988
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`lotes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `animal_tipo` VARCHAR(5) NULL DEFAULT NULL,
  `curral` INT(11) NOT NULL,
  `quantidade_animais` INT(11) NOT NULL,
  `oc` BIGINT(20) NULL DEFAULT NULL,
  `fornecedor` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `escala_lotes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `escala_lotes_id`),
  INDEX `fk_lotes_escala_lotes1_idx` (`escala_lotes_id` ASC) VISIBLE,
  CONSTRAINT `fk_lotes_escala_lotes`
    FOREIGN KEY (`escala_lotes_id`)
    REFERENCES `carcacas2_0`.`escala_lotes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 260
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`fotos_currais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`fotos_currais` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `imagem` MEDIUMTEXT NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `lotes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `lotes_id`),
  INDEX `fk_fotos_currais_lotes1_idx` (`lotes_id` ASC) VISIBLE,
  CONSTRAINT `fk_fotos_currais_lotes1`
    FOREIGN KEY (`lotes_id`)
    REFERENCES `carcacas2_0`.`lotes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 176
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`negociacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`negociacao` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`obs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`obs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `lote` INT(11) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`peso_carcaca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`peso_carcaca` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `peso` DOUBLE(10,2) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `escala_lotes_id` INT(11) NOT NULL,
  `animal_tipo_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `escala_lotes_id`, `animal_tipo_id`),
  INDEX `fk_peso_carcaca_escala_lotes1_idx` (`escala_lotes_id` ASC) VISIBLE,
  INDEX `fk_peso_carcaca_animal_tipo1_idx` (`animal_tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_peso_carcaca_animal_tipo1`
    FOREIGN KEY (`animal_tipo_id`)
    REFERENCES `carcacas2_0`.`animal_tipo` (`id`),
  CONSTRAINT `fk_peso_carcaca_escala_lotes1`
    FOREIGN KEY (`escala_lotes_id`)
    REFERENCES `carcacas2_0`.`escala_lotes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`produto_condenado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`produto_condenado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `carcacas2_0`.`vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carcacas2_0`.`vacina` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `escala_lote_id` INT(11) NOT NULL,
  `peso` DOUBLE(10,2) NOT NULL,
  PRIMARY KEY (`id`, `escala_lote_id`),
  INDEX `escala_lote_id` (`escala_lote_id` ASC) VISIBLE,
  CONSTRAINT `vacina_ibfk_1`
    FOREIGN KEY (`escala_lote_id`)
    REFERENCES `carcacas2_0`.`escala_lotes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 109
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
